report test results

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -24,7 +24,9 @@ jobs:
         run: ./gradlew test
       - name: execute integration tests
         run: ./gradlew integTest
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/*/*.xml'
       - run: echo "🍏 This job's status is ${{ job.status }}."
